version: 0.2
phases:
  pre_build:
    commands:
    - echo "Pre build"
  build:
    commands:
    - echo "Build started on $(date)"
    - python3 -m unittest -v
    - ./build.sh
    - echo "Build module"
  post_build:
    commands:
    - echo "Build completed on $(date)"
artifacts:
  files:
  - infrastructure/cf-lambdas.yaml
  - infrastructure/lambda-bucket.yaml
  - cicd/deployspec.yaml
  - cicd/deploy.sh
  - tmp/*
