version: 0.2
phases:
  pre_build:
    commands:
    - echo "Pre build"
  build:
    commands:
    - echo "Build started on $(date)"
    - chmod +x build.sh
    - ./build.sh
    - cd setup
    - python3 -m unittest -v
    - cd ../src
    - python3 -m unittest -v
    - cd ..
    - echo "Build module"
  post_build:
    commands:
    - echo "Build completed on $(date)"
artifacts:
  files:
  - infrastructure/cf-lambdas.yaml
  - infrastructure/lambda-bucket.yaml
  - cicd/deployspec.yaml
  - cicd/deploy.sh
  - tmp/**/*
