version: 0.2
phases:
  pre_build:
    commands:
    - echo "Pre build"
  build:
    commands:
    - python -m unittest -v
    - echo "Build started on $(date)"
    - echo "Build module"
  post_build:
    commands:
    - echo "Build completed on $(date)"
artifacts:
  files:
  - infrastructure/cf-template.yaml
  - infrastructure/cf-template.config
  - cicd/deployspec.yaml
  - cicd/deploy.sh
