AWSTemplateFormatVersion: 2010-09-09
Description: Pipeline for lambda deployment
Parameters:
  MyOAuth2Token:
    Type: String
Resources:
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
      ManagedPolicyArns:
      - !Ref CodePipelineBasicPolicy
      - !Ref PipelineArtifactsPolicy
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - !Ref CodeBuildBasicPolicy
      - !Ref PipelineArtifactsPolicy
      Policies:
      - PolicyName: SsmParameters
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - iam:CreateRole
            - s3:CreateBucket
            - s3:DeleteBucket
            - s3:PutBucketPolicy
            - s3:DeleteBucketPolicy
            - s3:PutBucketWebsite
            - s3:GetBucketWebsite
            - s3:DeleteBucketWebsite
            - s3:PutEncryptionConfiguration
            - s3:GetEncryptionConfiguration
            - cloudformation:DescribeStacks
            - cloudformation:GetTemplateSummary
            - cloudformation:CreateStack
            - cloudformation:UpdateStack
            - cloudformation:DeleteStack
            - cloudformation:SetStackPolicy
            - cloudformation:CreateChangeSet
            - cloudformation:DeleteChangeSet
            - cloudformation:DescribeChangeSet
            - cloudformation:ExecuteChangeSet
            Effect: Allow
            Resource: '*'
  CodePipelineBasicPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - codebuild:StartBuild
          - codebuild:BatchGetBuilds
          - iam:PassRole
          Effect: Allow
          Resource: '*'
  CodeBuildBasicPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          - ssm:DescribeParameters
          - ecr:GetAuthorizationToken
          Effect: Allow
          Resource: '*'
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  PipelineArtifactsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - s3:GetBucketVersioning
          - s3:ListBucketVersions
          Resource: !GetAtt PipelineArtifactsBucket.Arn
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:GetObjectVersion
          - s3:PutObject
          Resource: !Sub arn:aws:s3:::${PipelineArtifactsBucket}/*
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - !Ref CodeBuildBasicPolicy
      - !Ref PipelineArtifactsPolicy
      Policies:
      - PolicyName: SsmParameters
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - s3:PutObject
            - s3:ListBucket
            Effect: Allow
            Resource: !GetAtt PipelineArtifactsBucket.Arn
  CodeBuildBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Cache:
        Location: !Sub
          - ${BucketName}/cache/cussrobot-build
          - BucketName: !Ref PipelineArtifactsBucket
        Type: S3
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/buildspec.yaml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: false
        Image: aws/codebuild/python:3.7.1
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: AWS_ACCOUNT_ID
          Value: !Ref AWS::AccountId
      Name: CussRobotBuild
      ServiceRole: !Ref CodeBuildServiceRole
  CodeBuildBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/codebuild/${CodeBuildBuildProject}
      RetentionInDays: 30
  CodeBuildDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/deployspec.yaml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: false
        Image: aws/codebuild/python:3.7.1
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: AWS_ACCOUNT_ID
          Value: !Ref AWS::AccountId
      Name: CussRobotDeploy
      ServiceRole: !Ref CloudFormationRole
  CodeBuildDeployLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/codebuild/${CodeBuildDeployProject}
      RetentionInDays: 30
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactsBucket
      Name: CussRobotPipeline
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
      - Name: CodeCommitSources
        Actions:
        - Name: GetTemplateSources
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Provider: GitHub
            Version: 1
          Configuration:
            Branch: master
            PollForSourceChanges: true
            Owner: MartinDupont
            Repo: cussrobot
            OAuthToken: !Ref MyOAuth2Token
          OutputArtifacts:
          - Name: complete-sources
          RunOrder: 1
      - Name: Build
        Actions:
        - Name: ExecuteBuildspec
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: 1
            Provider: CodeBuild
          Configuration:
            ProjectName: !Ref CodeBuildBuildProject
          InputArtifacts:
          - Name: complete-sources
          OutputArtifacts:
          - Name: infrastructure-and-lambda-bundle
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: DeployLambdas
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: 1
            Provider: CodeBuild
          Configuration:
            ProjectName: !Ref CodeBuildDeployProject
          InputArtifacts:
          - Name: infrastructure-and-lambda-bundle
          RunOrder: 1
