AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to create an Cognito user pool.
Parameters:
  PriceClass:
    Type: String
    AllowedValues:
    - PriceClass_100
    - PriceClass_200
    - PriceClass_All
Resources:
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource: !Sub arn:aws:s3:::${ContentBucket}/*
          Principal:
            CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: TLSv1.2_2018
        Comment: Distributes react SPA
        PriceClass: !Ref PriceClass
        DefaultCacheBehavior:
          DefaultTTL: 31536000
          MinTTL: 20
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: staticS3Bucket
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
        - Id: staticS3Bucket
          DomainName: !GetAtt ContentBucket.DomainName
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: AccessIdentity for frontend
