AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket and lambda function for cussrobot.
Resources:
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256

