AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket and lambda function for cussrobot.
Resources:
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  LambdaArtifactsPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LambdaArtifactsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - s3:GetBucketVersioning
          - s3:ListBucket
          Resource: !GetAtt LambdaArtifactsBucket.Arn
          Principal:
            AWS: !Ref "AWS::AccountId"
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          Resource: !Sub arn:aws:s3:::${LambdaArtifactsBucket}/*
          Principal: "*"
Outputs:
  LambdaArtifactsBucketName:
    Value: !Ref LambdaArtifactsBucket
    Export:
      Name: lambda-artifacts-bucket-name
